# Generated by Django 2.1.7 on 2019-04-04 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(2, 'PE'), (0, 'polish'), (3, 'math'), (1, 'english'), (4, 'informatics')])),
                ('points', models.IntegerField()),
                ('grades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('answers', models.TextField()),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_exams.Exercise'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
