# Generated by Django 2.1.7 on 2019-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.IntegerField(choices=[(0, 'polish'), (2, 'PE'), (3, 'math'), (1, 'english'), (4, 'informatics')]),
        ),
    ]
