# Generated by Django 2.1.7 on 2019-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exam',
            name='exercise',
            field=models.ManyToManyField(to='manage_exams.Exercise'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.IntegerField(choices=[(0, 'polish'), (2, 'PE'), (4, 'informatics'), (1, 'english'), (3, 'math')]),
        ),
    ]
