# Generated by Django 2.1.7 on 2019-04-02 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_exams', '0002_auto_20190401_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.IntegerField(choices=[(0, 'polish'), (3, 'math'), (2, 'PE'), (1, 'english'), (4, 'informatics')]),
        ),
    ]
